# Generated by Django 4.2.11 on 2025-04-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('species', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('weight', models.FloatField()),
                ('weight_unit', models.CharField(choices=[('kg', 'Kilograms'), ('lb', 'Pounds')], max_length=2)),
                ('neutered', models.BooleanField()),
            ],
        ),
    ]
