# Generated by Django 5.2 on 2025-04-16 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_rename_weight_pet_current_weight_pet_expected_weight_and_more'),
        ('plan', '0002_alter_userplan_pet_alter_userplan_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplan',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.pet'),
        ),
    ]
