# Generated by Django 5.2 on 2025-05-07 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_remove_userfood_weight_per_serving_and_more'),
        ('plan', '0003_alter_userplan_pet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userplan',
            name='food_name',
        ),
        migrations.AddField(
            model_name='userplan',
            name='food',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='food.userfood'),
            preserve_default=False,
        ),
    ]
