# Generated by Django 5.2 on 2025-05-07 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0004_remove_userplan_food_name_userplan_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplan',
            name='food_name',
            field=models.CharField(default='TEST', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userplan',
            name='pet_name',
            field=models.CharField(default='TEST', max_length=255),
            preserve_default=False,
        ),
    ]
