# Generated by Django 5.2 on 2025-05-09 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_alter_pet_species'),
        ('plan', '0005_userplan_food_name_userplan_pet_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CombinedPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_daily_energy', models.FloatField()),
                ('total_daily_food_weight', models.FloatField()),
                ('total_servings', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.pet')),
                ('plan_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combined_as_a', to='plan.userplan')),
                ('plan_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combined_as_b', to='plan.userplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
