# Generated by Django 5.2 on 2025-05-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0006_combinedplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combinedplan',
            name='total_daily_food_weight',
        ),
        migrations.RemoveField(
            model_name='combinedplan',
            name='total_servings',
        ),
        migrations.AddField(
            model_name='combinedplan',
            name='plan_title',
            field=models.CharField(default='My Combined Plan', max_length=255),
        ),
    ]
