# Generated by Django 5.2 on 2025-05-13 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0007_remove_combinedplan_total_daily_food_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combinedplan',
            name='plan_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='combined_as_b', to='plan.userplan'),
        ),
    ]
