# Generated by Django 4.2.11 on 2025-04-02 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='activity_level',
            field=models.CharField(choices=[('low', 'Low'), ('moderate-low', 'Moderate Low'), ('moderate-high', 'Moderate High'), ('high', 'High'), ('very-high', 'Very High')], default='low', max_length=100),
        ),
        migrations.AddField(
            model_name='pet',
            name='condition_score',
            field=models.CharField(choices=[('severely-underweight', 'Severely Underweight'), ('underweight', 'Underweight'), ('ideal', 'Ideal'), ('overweight', 'Overweight'), ('obese', 'Obese')], default='ideal', max_length=100),
        ),
    ]
