# Generated by Django 5.1.7 on 2025-04-09 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=255)),
                ('food_type', models.CharField(choices=[('wet', 'Wet'), ('dry', 'Dry')], max_length=100)),
                ('packet_type', models.CharField(choices=[('tin', 'Tin'), ('sachet', 'Sachet'), ('carton', 'Carton'), ('high', 'High'), ('bag-of-dry-food', 'Bag of Dry Food')], max_length=100)),
                ('energy', models.FloatField()),
                ('energy_unit', models.CharField(choices=[('kj', 'kJ'), ('kcal', 'kcal')], max_length=50)),
                ('weight', models.FloatField()),
                ('weight_unit', models.CharField(choices=[('kg', 'Kilograms'), ('lb', 'Pounds')], max_length=2)),
                ('weight_per_packet', models.FloatField()),
                ('weight_per_serving', models.FloatField()),
                ('weight_per_packet_unit', models.CharField(choices=[('kg', 'Kilograms'), ('lb', 'Pounds')], max_length=2)),
                ('protein', models.FloatField()),
                ('fat', models.FloatField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
