# Generated by Django 5.1.7 on 2025-04-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_alter_userfood_weight_per_packet_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfood',
            name='weight_per_serving_unit',
            field=models.CharField(choices=[('kg', 'Kilograms'), ('lb', 'Pounds'), ('g', 'Grams')], default='g', max_length=2),
        ),
        migrations.AlterField(
            model_name='userfood',
            name='weight_per_packet_unit',
            field=models.CharField(choices=[('kg', 'Kilograms'), ('lb', 'Pounds'), ('g', 'Grams')], default='g', max_length=2),
        ),
    ]
