# Generated by Django 5.1.7 on 2025-04-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_userfood_weight_per_serving_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfood',
            name='weight_per_serving',
        ),
        migrations.RemoveField(
            model_name='userfood',
            name='weight_per_serving_unit',
        ),
        migrations.AlterField(
            model_name='userfood',
            name='packet_type',
            field=models.CharField(choices=[('tin', 'Tin'), ('sachet', 'Sachet'), ('carton', 'Carton'), ('scoop', 'scoop')], max_length=100),
        ),
        migrations.AlterField(
            model_name='userfood',
            name='weight_per_packet_unit',
            field=models.CharField(choices=[('kg', 'kilograms'), ('lb', 'pounds'), ('g', 'grams'), ('oz', 'ounces')], default='g', max_length=2),
        ),
        migrations.AlterField(
            model_name='userfood',
            name='weight_unit',
            field=models.CharField(choices=[('kg', 'kilograms'), ('lb', 'pounds'), ('g', 'grams'), ('oz', 'ounces')], max_length=2),
        ),
    ]
