# Generated by Django 5.1.7 on 2025-04-10 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_pet_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='weight',
            new_name='current_weight',
        ),
        migrations.AddField(
            model_name='pet',
            name='expected_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='activity_level',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pet',
            name='condition_score',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 - Severely Underweight'), (2, '2 - Underweight'), (3, '3 - Ideal'), (4, '4 - Overweight'), (5, '5 - Obese')], default=3),
        ),
        migrations.AlterField(
            model_name='pet',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pet',
            name='weight_unit',
            field=models.CharField(choices=[('kg', 'Kilograms'), ('lb', 'Pounds')], default='kg', max_length=2),
        ),
    ]
