# Generated by Django 5.2 on 2025-05-07 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_rename_weight_pet_current_weight_pet_expected_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.CharField(choices=[('cat', 'Cat'), ('dog', 'Dog')], default='cat', max_length=100),
        ),
    ]
